services:
  opcatlayer:
    image: opcatlabs/opcatlayer:latest
    entrypoint: ["bitcoind", "-datadir=/data/"]
    volumes:
      - ./data:/data
    ports:
      - "28444:28444"
      - "28443:28443"
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-datadir=/data/", "getblockchaininfo"]
      interval: 60s
      timeout: 10s
      retries: 3
